### ISSUE TITLE
Front End Resdesign

### ISSUE THREAD

**Issue by rugzombie** [Rug-Zombie/rug-zombie-frontend#41]
We have all the design elements and intend to release the redesign alongside the nFT marketplace on Jan 30th. 

Consult with nams on the design files, but we would like these ready to go asap!

**Comment by aubundy** [comment]
@nnamss For the desktop UI, the header and footer both become crowded on smaller screens. My laptop is 1280px wide and I have these issues:

- I need to scroll to the right to be able to see the green dropdown arrow
- Clicking on the green dropdown arrow doesn't do anything for me
- Launch and Connect buttons overlap navbar content
- Contact info on the left side of the footer is halfway cut off

Here are some screenshots of these below. Do you want me to fix these and any other desktop UI needs along with doing mobile UI?

<img width="1241" alt="Screen Shot 2022-01-02 at 1 19 45 PM" src="https://user-images.githubusercontent.com/37122448/147886966-40a7fdbc-94bc-4fc3-a1b9-cdd3611ba300.png">
<img width="1280" alt="Screen Shot 2022-01-02 at 1 19 54 PM" src="https://user-images.githubusercontent.com/37122448/147887036-c6cde98d-2dcd-4c99-a33f-3c6c718939e5.png">

**Comment by nnamdiarimah** [comment]
done
