### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by nnamdiarimah** [Rug-Zombie/rug-zombie-frontend#51]
We're nearing the end of the UI redesign and there's room for subtle improvements, @aubundy there's 2 things i need your help with!

**Issue 1:**
Branch: `graveyard-2`
The graveyard banner image on currently shrinks with the page, can we prevent the height of the banner from changing when screen size shrinks?
![Screen Shot 2022-02-01 at 11 04 10 PM](https://user-images.githubusercontent.com/10407499/152091372-6c2bbaf8-8f18-41bb-82a0-64f4a25de83e.png)
Opensea has a a good example of this:
![Screen Shot 2022-02-01 at 11 04 24 PM](https://user-images.githubusercontent.com/10407499/152091388-64269fe3-dc6f-4456-a15f-49c39a1f2d86.png)

**Issue 2:**
Branch: a copy of `rugzombie-2-remaining`
The second issue is the width of the graves. Grave width changes when they are open vs closed on some screen widths(tablet width)
![Screen Shot 2022-02-01 at 11 13 42 PM](https://user-images.githubusercontent.com/10407499/152092076-d6cd2c1f-e9f8-4f0b-98c6-6ec4790d3315.png)
![Screen Shot 2022-02-01 at 11 14 02 PM](https://user-images.githubusercontent.com/10407499/152092105-cd98f175-9d18-4d52-b912-0d1a44aab2a1.png)

**Comment by aubundy** [comment]
Just pushed updates for these. I didn't make a copy of `rugzombie-2-remaining`, but I left a note on #52 that I pushed an update
