### ISSUE TITLE
Redux refactoring

### ISSUE THREAD

**Issue by nnamdiarimah** [Rug-Zombie/rug-zombie-frontend#52]
Our repo currently uses `/redux` for our redux logic but this is changing with our ui redesign. 

On the `rugzombie-2-remaining` branch we moved graves, tombs and spawning pools redux logic to the `/state` directory and used a more responsive redux model. For this task we would like you to migrate the `nfts`  layer to the `/state` directory and use the new redux model to fetch their data.

The following is the data needed for each:
Nft:
- NftInfo:
  - total supply
- UserInfo:
  - ids of nfts owned by the connected wallet (We have a lot of NFTs so this will likely need to be queried in batches, [here's](https://github.com/Rug-Zombie/rug-zombie-frontend/blob/76d60051b352e402100a844ce113416244c51741/src/redux/fetch.ts#L599-L625) how we currently do it)

It would also be great if you help use remove any remaining pancake code thats not used by us, I wont be able to code for the next couple of days so feel free to work directly on the `rugzombie-2-remaining` branch. That way there will be no conflicts, I'll also let you know before I start coding again this weekend.

**Comment by aubundy** [comment]
I just pushed the GraveCard width correction to `rugzombie-2-remaining`, so be sure to update local branches with this fix
